import Head from 'next/head'
import { Inter } from 'next/font/google'
import DateTimeSlot from '@/components/DateTimeSlot'
import { useState } from 'react'
import moment from 'moment';

export default function Home() {
  const [show, setShow] = useState(false);

  const handleShow = (e) => {
    e.preventDefault();
    return setShow(true)
  }
  const time = moment()?.format('h:mm a');
  return (
    <>
      <Head>
        <title>Saarte Investeering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex items-center justify-center '>
        <div className='w-[780px] h-[932px] border mt-[84px] rounded-lg border-black p-8'>
          
          <p className='font-bold text-2xl text-center'>
            Time Now: { time}
          </p>
          <form onSubmit={(e)=>handleShow(e)} className='flex items-center justify-center gap-4 mt-8'>
            <label htmlFor="">Enter Meeting Duration(min)</label>
            <input type="text" name="" id="" className='border-2 rounded-lg p-4 font-bold text-xl text-center border-black w-[90px] h-[46px]'/>
          </form>
          {
            show && <DateTimeSlot></DateTimeSlot>
          }
        </div>
      </main>
    </>
  )
}
